desc = "dev config"
runmode = 1 #1:debug 2:release
concurnum = 5000

[pgsql]
hosts = ["182.16.39.218"]
ports = [5432]
user = "postgres"
password = "UM%&*qc!038"
dbname = "financass"

[redis]
hosts = ["redis://182.16.39.218:6379"]
password = "xjwl"
db = 9
maxActive = 3000
MaxIdle = 2000
IdleTimeoutSec = 240

[rabbitmq]
url = "amqp://game:123456@182.16.39.218:5672/game"
qgame = "gameTest"
qgamefeed = "gameFeed"

[log]
logfile = "item.log"
sqlog = "sql.log"

[authkey]
key = "widXNlcm5hb@#￥iOiLlvKD%￥uIkiLCJm&WxsX25*bWUiOiL"
subject = "happy new year"
privateKey = "./scripts/private_key.pem"
publickey = "./scripts/public_key.pem"

[fillter]
array = ["/getToken/","/logout/"]

[es]
user = "es"
passwd = "%^CV90)sd138~"
url = "http://192.168.0.222:9200"
logfile = "./eslog.log"



